name: Test

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: Find Comment
          uses: peter-evans/find-comment@v1
          id: fc
          with:
            body-includes: <!-- github-actions-screenshots -->
        - name: Log
          run: echo ${{ steps.fc.outputs.comment-id }}
