name: Test PR events

on:
  pull_request: 
    types: [labeled]

jobs:
  if: ${{ github.event.label.id == 2340250864 }}
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              echo ${{ toJSON(github.event) }}
