name: Test

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: Find Comment
          uses: peter-evans/find-comment@v1
          id: fc
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body-includes: <!-- github-actions-screenshots -->
        - name: Create
          if: ${{ steps.fc.outputs.comment-id == '' }} 
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              <!-- github-actions-screenshots -->
              Create
        - name: Update
          if: ${{ steps.fc.outputs.comment-id != '' }} 
          uses: peter-evans/create-or-update-comment@v1
          with:
            comment-id: ${{ steps.fc.outputs.comment-id }}
            body: |
              <!-- github-actions-screenshots -->
              Update
            edit-mode: replace  

            
