name: Testing

on:
  pull_request:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Take photo of github.com
      uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
      with:
        url: https://github.com
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
