name: Test manual trigger

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              echo "Hello world"
