name: Test manual trigger

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              echo `date -d "+1 hour" "+%a %H:%M"`
          env: 
            TZ: "/usr/share/zoneinfo/Europe/London"
