name: Testing

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.theguardian.com/uk
          destination: screenshot.png
          full-page: true
    
