name: Test manual trigger

on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        required: true
        description: Which environment should the build be released to? 

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              echo "Hello world ${{ github.event.inputs.deployment-environment }}"
