name: Test manual trigger

on:
  pull_request: 
    types: [labelled]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              echo ${{ github.event }}
