name: Test

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              sleep 120s
              echo "Hello world"
