name: Test

on:
  pull_request:

jobs:
  hello-world:
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: test
          run: |
              TEST=$(git show-ref master --hash)
              echo "Hello world ${TEST}"
