name: Test

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 100
        - name: test
          run: |
              TEST=$(git show-ref master --hash)
              echo "Hello world ${TEST}"
