# This is a basic workflow to help you get started with Actions

name: Test

on: deployment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: macos-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: test options
              run: |
                echo ${{ github.event_name }}
                echo ${{ github.event.environment }}    
